# Generated by Django 4.2.8 on 2024-04-29 16:17

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_location_city_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=app.utils.user_directory_path),
        ),
    ]
